name: 'Setup Base Environment'
description: 'Sets up the Base environment'
inputs:
  for-android:
    description: 'Whether to include android-specific setup'
    required: false
    default: 'false'
  for-ios:
    description: 'Whether to include ios-specific setup'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      name: Set up JDK 22
      with:
        java-version: '22'
        distribution: 'temurin'

    - uses: gradle/actions/setup-gradle@v4
      name: Setup Gradle

    - name: Setup Rust For Android
      shell: bash
      run: rustup target add aarch64-linux-android x86_64-linux-android
      if: ${{ inputs.for-android == 'true' }}

    - name: Setup Rust For iOS
      shell: bash
      run: rustup target add aarch64-apple-ios
      if: ${{ inputs.for-ios == 'true' }}

    - name: Spotless Check
      shell: bash
      run: ./gradlew spotlessCheck

    - name: Generate AboutLibraries Metadata
      shell: bash
      run: ./gradlew exportLibraryDefinitions